### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by gazpachoking** [conda-forge/jsonref-feedstock#7]
### Comment:

Want to update this to the latest version of the library? See https://github.com/gazpachoking/jsonref/issues/53

**Comment by jmpatri1** [comment]
Yes, I'd very much appreciate a current release in conda.  I just discovered JSONRef and am loving it. I'm currently releasing conda packages of my tool, and apparently can't bundle pip dependencies up with a conda package, although conda allows specifying pip deps in an environment.yaml file...

**Comment by geographika** [comment]
@gazpachoking - I'm also looking to get jsonref updated on conda-forge as it is a dependency of https://github.com/conda-forge/mappyfile-feedstock/
I also am not familiar with conda forge updates.. The maintainers are listed as @chapmanb and @marcelotrevisani

As I understand it if the current pull requests are closed - https://github.com/conda-forge/jsonref-feedstock/pulls then a bot will open a new one with for jsonref 1.1 and once that is merged it should be available in conda-forge. 

If granted access to this repo I can attempt this myself, but I think that would require a maintainer to add me.

**Comment by jgunstone** [comment]
agreed - would be great if this was up-to-date on conda
